# Radiant Savanna - Solar Lion (YELLOW REALM) - Multipliers:
hit1Multiplier=1
hit2Multiplier=1
hit3Multiplier=1
hit4Multiplier=2
hit5Multiplier=1
hit6Multiplier=1
hit7Multiplier=2
hit8Multiplier=1
hit9Multiplier=2
hit10Multiplier=1
hit11Multiplier=3